export const NODE_FORMSTATE = 'NODE_FORMSTATE';
export const NODE_LIST = 'NODE_LIST';
export const NODE_ONE = 'NODE_ONE';
export const DIRECTUSERFORMSTATE = 'DIRECTUSERFORMSTATE';
export const TOPICCATEGORYS_LIST = 'TOPICCATEGORYS_LIST';
// export const CONTENTTAG_LIST = 'CONTENTTAG_LIST';
