export const TOPIC_FORMSTATE = 'TOPIC_FORMSTATE';
export const TOPIC_LIST = 'TOPIC_LIST';
export const TOPIC_ONE = 'TOPIC_ONE';
export const DIRECTUSERFORMSTATE = 'DIRECTUSERFORMSTATE';
export const ADDNODEFORMSTATE = 'ADDNODEFORMSTATE';
export const TOPICCATEGORYS_LIST = 'TOPICCATEGORYS_LIST';
// export const CONTENTTAG_LIST = 'CONTENTTAG_LIST';
